# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [6]:
# Create a 1-dimensional NumPy array using np.array()
a1 = np.array([21,445,11,2212,44])

# Create a 2-dimensional NumPy array using np.array()
a2 = np.array([[1,14,445,11,21],[112,2,4,56,1]])

# Create a 3-dimensional Numpy array using np.array()
a3 = np.array([[[1,2,141],
              [14,14,1],
              [12,14,10]],
              [[7,21,11],
              [1,24,10],
              [1,24,41]]])

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [10]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
a1.shape , a1.size , a1.dtype , a1.ndim , type(a1)

((5,), 5, dtype('int32'), 1, numpy.ndarray)

In [11]:
# Attributes of 2-dimensional array
a2.shape , a2.size , a2.dtype , a2.ndim , type(a2)

((2, 5), 10, dtype('int32'), 2, numpy.ndarray)

In [12]:
# Attributes of 3-dimensional array
a3.shape , a3.size , a3.dtype , a3.ndim , type(a3)

((2, 3, 3), 18, dtype('int32'), 3, numpy.ndarray)

In [16]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
df = pd.DataFrame(a2)
df

0   1    2   3   4
0    1  14  445  11  21
1  112   2    4  56   1

In [19]:
# Create an array of shape (10, 2) with only ones
np.ones(shape=(10,2),dtype=int)

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [21]:
# Create an array of shape (7, 2, 3) of only zeros
np.zeros(shape=(7,2,3))

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [22]:
# Create an array within a range of 0 and 100 with step 3
np.arange(0,100,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [26]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
np.random.randint(10,size=(7,2))

array([[6, 1],
       [3, 1],
       [5, 2],
       [5, 7],
       [1, 3],
       [0, 1],
       [1, 9]])

In [27]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
np.random.random(size= (3,5))

array([[0.5898482 , 0.35502195, 0.47914795, 0.70056391, 0.68595818],
       [0.72353556, 0.70235414, 0.79026758, 0.84124208, 0.84351475],
       [0.549404  , 0.8545345 , 0.41720317, 0.85949686, 0.29507614]])

In [29]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
np.random.randint(0,high=10,size=(4,6))

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [35]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
ran_arr = np.random.randint(1,high=10,size= (3,7))
print(ran_arr)
# Find the unique numbers in the array you just created
print("Unique Array: ",np.unique(ran_arr))

[[7 1 1 9 9 4 9]
 [3 7 6 8 9 5 1]
 [3 8 6 8 9 4 1]]
Unique Array:  [1 3 4 5 6 7 8 9]


In [36]:
# Find the 0'th index of the latest array you created
ran_arr[0]

array([7, 1, 1, 9, 9, 4, 9])

In [37]:
# Get the first 2 rows of latest array you created
ran_arr[:2]

array([[7, 1, 1, 9, 9, 4, 9],
       [3, 7, 6, 8, 9, 5, 1]])

In [38]:
# Get the first 2 values of the first 2 rows of the latest array
ran_arr[:2,:2]

array([[7, 1],
       [3, 7]])

In [41]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
new_arr = np.random.randint(0,10,size=(3,5))
one  = np.ones(shape=(3,5))

In [42]:
# Add the two arrays together
new_arr + one

array([[ 1., 10.,  4.,  7.,  2.],
       [ 3.,  1.,  5.,  1.,  8.],
       [ 1.,  1.,  2.,  2.,  6.]])

In [43]:
# Create another array of ones of shape (5, 3)
one_new = np.ones(shape=(5,3))

In [46]:
# Try add the array of ones and the other most recent array together
one_new + one.reshape(5,3)

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [47]:
# Create another array of ones of shape (3, 5)
one2 = np.ones(shape=(3,5))

In [49]:
# Subtract the new array of ones from the other most recent array
one2 - one

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [50]:
# Multiply the ones array with the latest array
one2 * one

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [51]:
# Take the latest array to the power of 2 using '**'
one2 ** 2

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [52]:
# Do the same thing with np.square()
np.square(one2)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [53]:
# Find the mean of the latest array using np.mean()
np.mean(one2)

1.0

In [54]:
# Find the maximum of the latest array using np.max()
np.max(one2)

1.0

In [55]:
# Find the minimum of the latest array using np.min()
np.min(one)

1.0

In [57]:
# Find the standard deviation of the latest array
np.std(a2)

130.38255251374702

In [58]:
# Find the variance of the latest array
np.var(a2)

16999.609999999997

In [59]:
# Reshape the latest array to (3, 5, 1)
one2.reshape(3,5,1)

array([[[1.],
        [1.],
        [1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.],
        [1.],
        [1.]]])

In [60]:
# Transpose the latest array
one2.T

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

What does the transpose do?

In [61]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
arr1 = np.random.randint(0,10,size=(3,3))
arr2 = np.random.randint(0,10,size=(3,2))

In [62]:
# Perform a dot product on the two newest arrays you created
arr1.dot(arr2)

array([[ 60,  46],
       [ 12,  19],
       [ 78, 100]])

In [74]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
arr1 = np.random.randint(10,size=(4,3))
arr2 = np.random.randint(10,size=(4,2))

In [75]:
# Perform a dot product on the two newest arrays you created
np.dot(arr1,arr2)

ValueError: shapes (4,3) and (4,2) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?

In [76]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
np.dot(arr1.T,arr2)

array([[  8,  35],
       [ 98, 128],
       [ 36,  63]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [78]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
arr1 = np.random.randint(10,size=(3,3))
arr2 = np.random.randint(10,size=(3,3))

In [79]:
# Compare the two arrays with '>'
arr1 > arr2

array([[False, False,  True],
       [ True, False,  True],
       [False, False,  True]])

What happens when you compare the arrays with `>`?

In [80]:
# Compare the two arrays with '>='
arr1>=arr2

array([[False, False,  True],
       [ True, False,  True],
       [False,  True,  True]])

In [82]:
# Find which elements of the first array are greater than 7
arr1
arr1


array([[False, False,  True],
       [ True, False, False],
       [False, False, False]])

In [83]:
# Which parts of each array are equal? (try using '==')
arr1 == arr2

array([[False, False, False],
       [False, False, False],
       [False,  True, False]])

In [86]:
# Sort one of the arrays you just created in ascending order
np.sort(arr1)

array([[4, 6, 8],
       [2, 2, 8],
       [2, 3, 7]])

In [87]:
# Sort the indexes of one of the arrays you just created
np.argsort(a2)

array([[0, 3, 1, 4, 2],
       [4, 1, 2, 3, 0]], dtype=int64)

In [89]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(a2) 

2

In [90]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(a2)

0

In [91]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(a2,axis=1)

array([2, 0], dtype=int64)

In [92]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmin(a2,axis=0)

array([0, 1, 1, 0, 1], dtype=int64)

In [93]:
# Create an array of normally distributed random numbers
np.random.randn(1,10)

array([[ 0.85399779,  1.78859386,  0.56689407, -0.16450043, -0.14299093,
        -1.9345702 ,  0.15065904, -0.01571494, -1.33007407, -0.02528763]])

In [94]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.linspace(1,100)

array([  1.        ,   3.02040816,   5.04081633,   7.06122449,
         9.08163265,  11.10204082,  13.12244898,  15.14285714,
        17.16326531,  19.18367347,  21.20408163,  23.2244898 ,
        25.24489796,  27.26530612,  29.28571429,  31.30612245,
        33.32653061,  35.34693878,  37.36734694,  39.3877551 ,
        41.40816327,  43.42857143,  45.44897959,  47.46938776,
        49.48979592,  51.51020408,  53.53061224,  55.55102041,
        57.57142857,  59.59183673,  61.6122449 ,  63.63265306,
        65.65306122,  67.67346939,  69.69387755,  71.71428571,
        73.73469388,  75.75510204,  77.7755102 ,  79.79591837,
        81.81632653,  83.83673469,  85.85714286,  87.87755102,
        89.89795918,  91.91836735,  93.93877551,  95.95918367,
        97.97959184, 100.        ])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.